{% if GIT_DESCRIBE_NUMBER == '0' %}
{% set version = GIT_DESCRIBE_TAG %}
{% else %}
{% set version = GIT_DESCRIBE_TAG + '.dev' + GIT_DESCRIBE_NUMBER %}
{% endif %}
package:
  name: jupyter-docx-bundler
  version: {{version}}

source:
  path: ..

build:
  skip: True  # [py<36]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - setuptools-scm
  run:
    - lxml
    - nbconvert >=5.5
    - notebook >=5.0
    - pandas
    - pandoc >=2.11
    - pandocfilters
    - pypandoc >=1.4
    - python
    - requests
    - tabulate
    - tornado

test:
  imports:
    - jupyter_docx_bundler
  requires:
    - ipython >=7.0
    - matplotlib-base >=3.1
    - mock
    - nbformat
    - pillow >=6.0.0
    - pytest
    - pytest-cov
    - pytest-lazy-fixture
    - sympy
  commands:
    - pytest --pyargs jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
