{% set version = GIT_DESCRIBE_TAG %}
package:
  name: jupyter-docx-bundler
  version: {{version}}

source:
  path: ..

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools >=38.6.0
    - setuptools_scm
  run:
    - python >=3.6
    - notebook >=5.0
    - pypandoc >=1.4
    - nbconvert >=5.5
    - pandoc >=2.0
    - requests
    - tornado

test:
  imports:
    - jupyter_docx_bundler
  requires:
    - matplotlib >=3.1
    - mock
    - nbformat
    - pillow >= 6.0.0
    - pytest
    - pytest-azurepipelines >=0.6.0
    - pytest-cov
    - pytest-lazy-fixture
  commands:
    - pytest --pyargs jupyter_docx_bundler

about:
  home: https://github.com/m-rossi/jupyter-docx-bundler
  license: MIT
  license_file: LICENSE
  summary: Jupyter bundler extension to export notebook as a docx file
